# Generated by Django 3.2.16 on 2022-10-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbca", "0004_alter_application_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(max_length=127),
        ),
    ]
