# Generated by Django 3.2.16 on 2022-10-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbca', '0005_alter_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
