# Generated by Django 3.2.16 on 2022-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alternate_supplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='day_rate',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='finance_bp_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fta_further_infomation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fta_how_filled',
            field=models.CharField(blank=True, choices=[('FAIR_OPEN_COMPETITION', 'Fair & open competition'), ('OTHER_ROUTES', 'Other routes')], max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hrbp_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ir35_consideration',
            field=models.CharField(blank=True, choices=[('IN_SCOPE', 'In Scope - SCS signed off'), ('OUT_OF_SCOPE', 'Out of scope - SCS signed off')], max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='new_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scs_adverts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scs_assignments_lengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tda_further_infomation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tda_how_filled',
            field=models.CharField(blank=True, choices=[('EOI', 'EOI'), ('DIRECT_APPOINTMENT', 'Direct appointment')], max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='via_ams',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='why_contingent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
