# Generated by Django 3.2.16 on 2022-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_auto_20221014_0741"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="pdf",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
