name: Create ETF Services

env:
  DOCKER_BUILDKIT: 1

on:
  workflow_dispatch:
    branches:
      - sandbox
      - develop
      - staging

jobs:
  create_cfservices:
    if:  ${{ github.event_name != 'release' && github.ref_name != 'prod' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get non-prod space name
        if:  ${{ github.event_name != 'release' }}
        uses: kanga333/variable-mapper@v0.2.2
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "sandbox": {"CF_SPACE": "sandbox"},
              "demo": {"CF_SPACE": "demo"},
              "temp": {"CF_SPACE": "temp"},
              "develop": {"CF_SPACE": "develop"},
              "staging": {"CF_SPACE": "staging"},
              "pentest": {"CF_SPACE": "pentest"},
              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
            }

      - name: Get prod space name
        if:  ${{ github.event_name == 'release' }}
        uses: kanga333/variable-mapper@v0.2.2
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "v?.?.?": {"CF_SPACE": "prod"},
              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
            }

      - name: Download CF CLI
        working-directory: ./cfscripts
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        working-directory: ./cfscripts
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: Run etf Services Script
        working-directory: ./cfscripts
        run: |
            ./etf-services.sh

      - uses: actions/checkout@v2
      - name: Slack Notification
        continue-on-error: true
        if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
          SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
